package com.Models;
// Generated 18/05/2015 05:32:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Inmuebles generated by hbm2java
 */
@Entity
@Table(name="inmuebles"
    ,catalog="data_home"
)
public class Inmuebles  implements java.io.Serializable {


     private long id;
     private Personas personas;
     private TiposHabitacion tiposHabitacion;
     private TiposInmuebles tiposInmuebles;
     private int numeroHabitaciones;
     private Integer numeroCamas;
     private int numeroBanos;
     private int estrato;
     private int capacidad;
     private String direccion;
     private String descripcion;
     private String estado;
     private String imagen;
     private Set suscripcioneses = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set valoracioneses = new HashSet(0);

    public Inmuebles() {
    }

    public Inmuebles(long id) {
        this.id = id;
    }

    
	
    public Inmuebles(long id, Personas personas, TiposHabitacion tiposHabitacion, TiposInmuebles tiposInmuebles, int numeroHabitaciones, int numeroBanos, int estrato, int capacidad, String direccion, String descripcion, String imagen) {
        this.id = id;
        this.personas = personas;
        this.tiposHabitacion = tiposHabitacion;
        this.tiposInmuebles = tiposInmuebles;
        this.numeroHabitaciones = numeroHabitaciones;
        this.numeroBanos = numeroBanos;
        this.estrato = estrato;
        this.capacidad = capacidad;
        this.direccion = direccion;
        this.descripcion = descripcion;
        this.imagen = imagen;
    }
    public Inmuebles(long id, Personas personas, TiposHabitacion tiposHabitacion, TiposInmuebles tiposInmuebles, int numeroHabitaciones, Integer numeroCamas, int numeroBanos, int estrato, int capacidad, String direccion, String descripcion, String estado, String imagen, Set suscripcioneses, Set reservas, Set valoracioneses) {
       this.id = id;
       this.personas = personas;
       this.tiposHabitacion = tiposHabitacion;
       this.tiposInmuebles = tiposInmuebles;
       this.numeroHabitaciones = numeroHabitaciones;
       this.numeroCamas = numeroCamas;
       this.numeroBanos = numeroBanos;
       this.estrato = estrato;
       this.capacidad = capacidad;
       this.direccion = direccion;
       this.descripcion = descripcion;
       this.estado = estado;
       this.imagen = imagen;
       this.suscripcioneses = suscripcioneses;
       this.reservas = reservas;
       this.valoracioneses = valoracioneses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_arrendador", nullable=false)
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_habitacion", nullable=false)
    public TiposHabitacion getTiposHabitacion() {
        return this.tiposHabitacion;
    }
    
    public void setTiposHabitacion(TiposHabitacion tiposHabitacion) {
        this.tiposHabitacion = tiposHabitacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_inmueble", nullable=false)
    public TiposInmuebles getTiposInmuebles() {
        return this.tiposInmuebles;
    }
    
    public void setTiposInmuebles(TiposInmuebles tiposInmuebles) {
        this.tiposInmuebles = tiposInmuebles;
    }

    
    @Column(name="numero_habitaciones", nullable=false)
    public int getNumeroHabitaciones() {
        return this.numeroHabitaciones;
    }
    
    public void setNumeroHabitaciones(int numeroHabitaciones) {
        this.numeroHabitaciones = numeroHabitaciones;
    }

    
    @Column(name="numero_camas")
    public Integer getNumeroCamas() {
        return this.numeroCamas;
    }
    
    public void setNumeroCamas(Integer numeroCamas) {
        this.numeroCamas = numeroCamas;
    }

    
    @Column(name="numero_banos", nullable=false)
    public int getNumeroBanos() {
        return this.numeroBanos;
    }
    
    public void setNumeroBanos(int numeroBanos) {
        this.numeroBanos = numeroBanos;
    }

    
    @Column(name="estrato", nullable=false)
    public int getEstrato() {
        return this.estrato;
    }
    
    public void setEstrato(int estrato) {
        this.estrato = estrato;
    }

    
    @Column(name="capacidad", nullable=false)
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

    
    @Column(name="direccion", nullable=false, length=60)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="imagen", nullable=false, length=100)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inmuebles")
    public Set getSuscripcioneses() {
        return this.suscripcioneses;
    }
    
    public void setSuscripcioneses(Set suscripcioneses) {
        this.suscripcioneses = suscripcioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inmuebles")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inmuebles")
    public Set getValoracioneses() {
        return this.valoracioneses;
    }
    
    public void setValoracioneses(Set valoracioneses) {
        this.valoracioneses = valoracioneses;
    }




}


