package com.Models;
// Generated 18/05/2015 05:32:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name="personas"
    ,catalog="data_home"
)
public class Personas  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String apellido;
     private String direccion;
     private String fijo;
     private String celular;
     private String sexo;
     private Date fechaNac;
     private Set suscripcioneses = new HashSet(0);
     private Usuarios usuarios;
     private Set reservas = new HashSet(0);
     private Set inmuebleses = new HashSet(0);
     private Set valoracioneses = new HashSet(0);

    public Personas() {
    }

    public Personas(long id) {
        this.id = id;
    }
    public Personas(long id, String nombre, String apellido, String direccion, String sexo, Date fechaNac) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.sexo = sexo;
        this.fechaNac = fechaNac;
    }
    public Personas(long id, String nombre, String apellido, String direccion, String fijo, String celular, String sexo, Date fechaNac, Set suscripcioneses, Usuarios usuarios, Set reservas, Set inmuebleses, Set valoracioneses) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.fijo = fijo;
       this.celular = celular;
       this.sexo = sexo;
       this.fechaNac = fechaNac;
       this.suscripcioneses = suscripcioneses;
       this.usuarios = usuarios;
       this.reservas = reservas;
       this.inmuebleses = inmuebleses;
       this.valoracioneses = valoracioneses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=20)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="fijo", length=7)
    public String getFijo() {
        return this.fijo;
    }
    
    public void setFijo(String fijo) {
        this.fijo = fijo;
    }

    
    @Column(name="celular", length=10)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="sexo", nullable=false, length=15)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nac", nullable=false, length=10)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personas")
    public Set getSuscripcioneses() {
        return this.suscripcioneses;
    }
    
    public void setSuscripcioneses(Set suscripcioneses) {
        this.suscripcioneses = suscripcioneses;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="personas")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personas")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personas")
    public Set getInmuebleses() {
        return this.inmuebleses;
    }
    
    public void setInmuebleses(Set inmuebleses) {
        this.inmuebleses = inmuebleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personas")
    public Set getValoracioneses() {
        return this.valoracioneses;
    }
    
    public void setValoracioneses(Set valoracioneses) {
        this.valoracioneses = valoracioneses;
    }




}


