package com.Models;
// Generated 18/05/2015 05:32:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="data_home"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Usuarios  implements java.io.Serializable {


     private Long idPersona;
     private Personas personas;
     private Roles roles;
     private String nombre;
     private String clave;
     private String lastname;
     private String estado;

    public Usuarios() {
    }

    public Usuarios(Personas personas, Roles roles, String nombre, String clave, String lastname, String estado) {
       this.personas = personas;
       this.roles = roles;
       this.nombre = nombre;
       this.clave = clave;
       this.lastname = lastname;
       this.estado = estado;
    }

    public Usuarios(Long idPersona) {
        this.idPersona = idPersona;
    }
    
    
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="personas"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_persona", unique=true, nullable=false)
    public Long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Long idPersona) {
        this.idPersona = idPersona;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="clave", nullable=false, length=50)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="lastname", nullable=false, length=200)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="estado", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


