package com.Models;
// Generated 18/05/2015 05:32:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Valoraciones generated by hbm2java
 */
@Entity
@Table(name="valoraciones"
    ,catalog="data_home"
)
public class Valoraciones  implements java.io.Serializable {


     private Long id;
     private Inmuebles inmuebles;
     private Personas personas;
     private Integer calificacion;
     private String comentario;

    public Valoraciones() {
    }

	
    public Valoraciones(Inmuebles inmuebles, Personas personas, String comentario) {
        this.inmuebles = inmuebles;
        this.personas = personas;
        this.comentario = comentario;
    }
    public Valoraciones(Inmuebles inmuebles, Personas personas, Integer calificacion, String comentario) {
       this.inmuebles = inmuebles;
       this.personas = personas;
       this.calificacion = calificacion;
       this.comentario = comentario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_inmueble", nullable=false)
    public Inmuebles getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Inmuebles inmuebles) {
        this.inmuebles = inmuebles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_valorador", nullable=false)
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }

    
    @Column(name="calificacion")
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }

    
    @Column(name="comentario", nullable=false)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


